# Project Information
site_name: Vantage Documentation
site_url: https://vantageproject.org
site_description: 'Documentation for Vantage: A large, verified mathematical knowledge base in Lean 4'

# Repository
repo_url: https://github.com/justincasher/vantage
repo_name: 'vantage'          # Name displayed for the link
edit_uri: 'edit/master/docs/' # Allows direct links to edit pages on GitHub (adjust 'main' if your branch is different)

# Theme Configuration (using mkdocs-material)
theme:
  name: material
  logo: images/favicon.png 
  favicon: images/favicon.png
  features:
    - navigation.tabs     # Use top-level sections as tabs
    - navigation.sections # Expand sections in the side navigation
    - navigation.top      # Back-to-top button
    - search.suggest      # Autocomplete suggestions in search
    - search.highlight    # Highlight search terms on results page
    - content.code.annotate # Allows code annotations
    - content.code.copy   # Copy button for code blocks
    - header.autohide     # Automatically hide the header
  palette: # Allow light/dark mode toggle
    - scheme: default     # Default light mode
      primary: deep purple
      accent: deep blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate       # Default dark mode
      primary: deep purple
      accent: deep blue
      toggle:
        icon: material/brightness-2
        name: Switch to light mode

# Navigation Structure (Manually defining API Reference)
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started':
    - 'Installation & Setup': 'getting-started/index.md'
    - 'Configuration': 'getting-started/configuration.md'
    - 'Usage': 'getting-started/usage.md'
  - 'API Reference':
    - 'Overview': 'reference/index.md'
    - 'Config':
        - 'Config Loader': 'reference/config/loader.md'
    - 'Knowledge Base (KB)':
        - 'KB Search': 'reference/kb/search.md'
        - 'KB Storage': 'reference/kb/storage.md'
    - 'LaTeX':
        - 'LaTeX Processor': 'reference/latex/processor.md'
    - 'Lean':
        - 'Lean Interaction': 'reference/lean/interaction.md'
        - 'Lean LSP Analyzer': 'reference/lean/lsp_analyzer.md'
        - 'Lean LSP Client': 'reference/lean/lsp_client.md'
        - 'Lean Processor': 'reference/lean/processor.md'
        - 'Lean Proof Repair': 'reference/lean/proof_repair.md'
    - 'LLM':
        - 'LLM Caller': 'reference/llm/caller.md'
  - 'Contributing':
    - 'How to Contribute': 'contributing/index.md'
    - 'Testing': 'contributing/testing.md'
    - 'Coding Style': 'contributing/coding_style_guidelines.md'
    - 'Code of Conduct': 'contributing/code_of_conduct.md'



# Markdown Extensions (Enable extra formatting features)
markdown_extensions:
  - admonition           # Adds nice colored boxes for notes, warnings, etc.
  - pymdownx.details     # Collapsible sections
  - pymdownx.superfences # Allows nesting code blocks, diagrams, etc.
  - pymdownx.highlight:  # Code highlighting configuration
      anchor_linenums: true
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.snippets    # Include parts of other files
  - pymdownx.tabbed:     # Tabbed content blocks
      alternate_style: true
  - toc:                 # Table of contents generation
      permalink: true    # Add links to headings

# Plugins Configuration
plugins:
  - search # Built-in search plugin
  - gen-files: # Generates files before build
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings: # Renders docstrings from Python code
      handlers:
        python: # Using the Python handler
          options:
            # --- Core Parsing Options ---
            docstring_style: google          # Sets the expected docstring format (e.g., google, numpy, sphinx).

            # --- Member Rendering Control ---
            members_order: source            # Order members (functions, classes) as they appear in the source code file.
            show_docstring_functions: true   # Render the full docstring body for functions and methods.
            show_docstring_classes: true     # Render the full docstring body for classes.
            # Note: Options like show_docstring_parameters, _raises, _attributes, _description, etc., default to true.

            # --- Presentation and Organization ---
            show_root_heading: true          # Add a top-level heading for the object being documented (e.g., the module name).
            show_category_heading: true      # Add category headings like "Functions", "Classes" when listing members.
            group_by_category: true          # Group listed members by their category (functions together, classes together).
            show_bases: true                 # For classes, show the base classes they inherit from.
            show_signature_annotations: true # Include type hints (annotations) in the rendered function/method signatures.
