# Project Information
site_name: Vantage Documentation
site_url: https://vantageproject.org
site_description: 'Documentation for Vantage: A large, verified mathematical knowledge base in Lean 4'

# Repository
repo_url: https://github.com/justincasher/vantage
repo_name: 'vantage'          # Name displayed for the link
edit_uri: 'edit/master/docs/' # Allows direct links to edit pages on GitHub (adjust 'main' if your branch is different)

# Theme Configuration (using mkdocs-material)
theme:
  name: material
  # logo: assets/logo.png # Optional: Add a logo image file to docs/assets/
  # favicon: assets/favicon.png # Optional: Add a favicon image file to docs/assets/
  features:
    - navigation.tabs     # Use top-level sections as tabs
    - navigation.sections # Expand sections in the side navigation
    - navigation.top      # Back-to-top button
    - search.suggest      # Autocomplete suggestions in search
    - search.highlight    # Highlight search terms on results page
    - content.code.annotate # Allows code annotations
    - content.code.copy   # Copy button for code blocks
  palette: # Allow light/dark mode toggle
    - scheme: default     # Default light mode
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate       # Default dark mode
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Navigation Structure (Manually defining API Reference)
nav:
  - 'Welcome': 'index.md'
  - 'Getting Started': 
    - 'Installation & Setup': 'installation.md'
    - 'Configuration': 'configuration.md'
    - 'Usage': 'usage.md'
  - 'API Reference': 
    - 'Overview': 'reference/index.md' 
    - 'KB Search': 'reference/kb_search.md' 
    - 'KB Storage': 'reference/kb_storage.md'
    - 'LaTeX Processor': 'reference/latex_processor.md'
    - 'Lean Interaction': 'reference/lean_interaction.md'
    - 'Lean Processor': 'reference/lean_processor.md'
    - 'Lean Proof Repair': 'reference/lean_proof_repair.md'
    - 'LLM Call': 'reference/llm_call.md'
  - 'Contributing':
    - 'How to Contribute': 'contributing.md'
    - 'Testing': 'testing.md'
    - 'Testing': 'coding_style_guidelines.md'
    - 'Code of Conduct': 'code_of_conduct.md'

# Markdown Extensions (Enable extra formatting features)
markdown_extensions:
  - admonition           # Adds nice colored boxes for notes, warnings, etc.
  - pymdownx.details     # Collapsible sections
  - pymdownx.superfences # Allows nesting code blocks, diagrams, etc.
  - pymdownx.highlight:  # Code highlighting configuration
      anchor_linenums: true
  - pymdownx.inlinehilite # Inline code highlighting
  - pymdownx.snippets    # Include parts of other files
  - pymdownx.tabbed:     # Tabbed content blocks
      alternate_style: true
  - toc:                 # Table of contents generation
      permalink: true    # Add links to headings

# Plugins Configuration
plugins:
  - search # Built-in search plugin
  - gen-files: # Generates files before build
      scripts:
        - scripts/gen_ref_pages.py
  - mkdocstrings: # Renders docstrings from Python code
      handlers:
        python: # Using the Python handler
          options:
            # --- Core Parsing Options ---
            docstring_style: google          # Sets the expected docstring format (e.g., google, numpy, sphinx).

            # --- Member Rendering Control ---
            members_order: source            # Order members (functions, classes) as they appear in the source code file.
            show_docstring_functions: true   # Render the full docstring body for functions and methods.
            show_docstring_classes: true     # Render the full docstring body for classes.
            # Note: Options like show_docstring_parameters, _raises, _attributes, _description, etc., default to true.

            # --- Presentation and Organization ---
            show_root_heading: true          # Add a top-level heading for the object being documented (e.g., the module name).
            show_category_heading: true      # Add category headings like "Functions", "Classes" when listing members.
            group_by_category: true          # Group listed members by their category (functions together, classes together).
            show_bases: true                 # For classes, show the base classes they inherit from.
            show_signature_annotations: true # Include type hints (annotations) in the rendered function/method signatures.
