[build-system]
requires = ["setuptools>=61.0"] 
build-backend = "setuptools.build_meta" 

[project]
name = "vantage"  
version = "0.1.0"       
description = "A project for automating Lean formalization."
readme = "README.md"     
requires-python = ">=3.8" 
