# .github/workflows/deploy-docs.yml

name: Deploy Documentation to Pages

on:
  # Trigger the workflow on pushes to the master branch
  push:
    branches:
      - master # Make sure this matches your default branch name

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read  # Allows checkout
  pages: write    # Allows deployment to Pages
  id-token: write # Allows OIDC token generation (needed for newer deployment methods)

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    name: Build Docs
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11 # Or your project's Python version
          cache: 'pip' # Cache pip dependencies
      - name: Install documentation dependencies
        run: pip install -r docs/requirements.txt # Use the dedicated docs requirements
      - name: Install project package
        run: pip install . # Assumes pyproject.toml or setup.py is in the root
      - name: Build MkDocs site
        run: mkdocs build --verbose # Build the site into the 'site' directory

      # This step uploads the built site artifacts
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire directory
          path: './site' # Default location for mkdocs build output

  # Deployment job
  deploy:
    name: Deploy Docs
    needs: build # Run after the build job is complete
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }} # URL provided after deployment
    runs-on: ubuntu-latest
    steps:
      # This step does the actual deployment to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        # No 'with:' required if using the uploaded artifact